In [1]:
import numpy as np

## Numpy 연산

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,1],[1,6]])

In [7]:
A

array([[1, 2],
       [3, 4]])

In [8]:
B

array([[3, 1],
       [1, 6]])

In [9]:
A+B

array([[ 4,  3],
       [ 4, 10]])

In [11]:
A*B

array([[ 3,  2],
       [ 3, 24]])

In [13]:
C = 10 

In [14]:
A+C

array([[11, 12],
       [13, 14]])

In [15]:
D = np.array([10,20])

In [17]:
A+D

array([[11, 22],
       [13, 24]])

In [19]:
np.dot(A,B) #행렬의 내적 / A*B와 다름 혼동될수 있음.

array([[ 5, 13],
       [13, 27]])

In [26]:
np.dot(A,D)

array([ 50, 110])

In [35]:
E = np.array,([[1],[3],[5]])

In [38]:
A

array([[1, 2],
       [3, 4]])

In [39]:
E

(<function numpy.array>, [[1], [3], [5]])

In [37]:
np.dot(A,E)

<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


TypeError: unsupported operand type(s) for *: 'int' and 'builtin_function_or_method'