## 활성화함수

In [1]:
import numpy as np

In [3]:
def step_function(x):
    if x > 0:
        return 1
    elif x <= 0 :
        return 0

In [5]:
step_function(3)

1

## Numpy를 활용한 계단함수

In [13]:
x = np.array([-1.0, 5.0, 2.0])

In [14]:
y = x >0

In [15]:
y

array([False,  True,  True])

In [17]:
y.astype(np.int64)

array([0, 1, 1], dtype=int64)

In [18]:
def step_function(x):
    y = x > 0 
    return y.astype(np.int64)

In [19]:
x =np.array([-1.0,5.0,2.0])
step_function(x)

array([0, 1, 1], dtype=int64)

##### 계단함수는 미분이 안됨 / 시그모이드 함수는 미분이 가능

## 시그모이드 함수

In [25]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [35]:
x =np.array([-1.0,0,5.0,2.0])
sigmoid(x)

array([0.26894142, 0.5       , 0.99330715, 0.88079708])

## RELU 함수 구현

In [38]:
def relu(X):
    return np.maximum(0,x)

In [40]:
x =np.array([-1.0,0,5.0,2.0,100.0])
relu(x)

array([  0.,   0.,   5.,   2., 100.])