In [1]:
import numpy as np

In [2]:
X  =np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])

In [3]:
Y = np.dot(X,W)

In [5]:
B = np.array([1,1,1])

In [13]:

X1 = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])
A1 = np.dot(X1,W1)+B1

In [14]:
A1

array([0.3, 0.7, 1.1])

## 1층

In [16]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])
A1 = np.dot(X1,W1)+B1

In [18]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [21]:
Z1 = sigmoid(A1)

## 2층

In [29]:
B2 = np.array([0.1,0.2])
W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
A2 = np.dot(Z1,W2)+B2

In [32]:
Z2 = sigmoid(A2)

In [33]:
Z2

array([0.62624937, 0.7710107 ])

## 3층

In [38]:
W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])
A3 = np.dot(Z2,W3)+B3

In [42]:
A3

array([0.31682708, 0.69627909])

In [43]:
def identity_function(x):
    return x

In [44]:
Y = identity_function(A3)

In [45]:
Y

array([0.31682708, 0.69627909])

## 전체코드

In [46]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

In [47]:
def identity_function(x):
    return x

In [58]:
def init_network(): #마지막 출력값
    network = {}
    
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    
    return network

In [63]:
def forward(network, x) :
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid(a2)
    
    a3 = np.dot(z2,W3) + b3
    y = identity_function(a3)
    
    return y

In [64]:
network = init_network()

In [65]:
x = np.array([1.0,0.5])

In [66]:
y = forward(network,x)

In [67]:
y

array([0.31682708, 0.69627909])

## 소프트 맥스 함수

In [68]:
a = np.array([0.3, 2.9, 4.0])

In [84]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [85]:
softmax(a)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [86]:
np.sum(softmax(a))

1.0

In [87]:
a = np.array([1010,1000,990])

In [98]:
softmax(a)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])