In [38]:
class MulLayer :
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self,x,y):
        self.x = x
        self.y = y
        
        out = x * y
        
        return out
    
    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x
        
        return dx, dy

In [66]:
apple = 100
apple_num =2
tax = 1.1

In [67]:
mul_apple = MulLayer()
mul_tax_layer = MulLayer()

In [68]:
apple_price = mul_apple.forward(apple,apple_num)
mul_tax_layer.forward(tax,apple_price)

220.00000000000003

In [69]:
dprice = 1

In [70]:
dapple_price, dtax = mul_tax_layer.backward(dprice)

In [71]:
dapple, dapple_num = mul_tax_layer.backward(dapple_price)

In [72]:
print(dapple_price, dtax, dapple, dapple_num)

200 1.1 40000 220.00000000000003


In [79]:
class AddLayer :
    def __init__(self) :
        pass
    def forward(self, x, y) :

        out = x + y
        
        return out
    
    def backward(self,dout):
        dx =  dout * 1
        dy =  dout * 1
        
        return dx, dy

In [88]:
apple = 100
apple_num = 2
apple_tax = 1.1
orange = 150
orange_num = 3
orange_tax = 1.1

In [89]:
mul_apple = MulLayer()
add_fruit = AddLayer()
mul_tax_layer = MulLayer()
mul_orange = MulLayer()

In [92]:
ap1 = mul_apple.forward(apple, apple_num)
or1 = mul_orange.forward(orange,orange_num)

In [96]:
fruit_tax = add_fruit.forward(ap1,or1)

In [98]:
final = mul_tax_layer.forward(fruit_tax,apple_tax)

In [99]:
print(ap1, or1, fruit_tax, final)

200 450 650 715.0000000000001


In [100]:
dprice = 1

In [102]:
dfruit_tax,dtax = mul_tax_layer.backward(dprice)

In [106]:
dap1, dor1 = add_fruit.backward(dfruit_tax)

In [111]:
dapple, dapple_num = mul_apple.backward(dap1)

In [112]:
dorange, dorange_num = mul_orange.backward(dor1)

In [113]:
print(dfruit_tax, dtax, dap1, dor1, dapple, dapple_num, dorange, dorange_num)

1.1 650 1.1 1.1 2.2 110.00000000000001 3.3000000000000003 165.0


----------------------------------------------------

In [143]:
class Relu :
    def __init__(self):
        self.mask = None
    def forward(self, x):
        self.mask  = (x<=0)
        out = x.copy()
        out[self.mask] = 0
        
    def backward(self, dout) :
        dout[self.mask] = 0
        dx = dout
        
        return dx

In [144]:
import numpy as np

In [145]:
x = np.array([[1.0,0.5],[-2.0,3.0]])

In [146]:
x <= 0

array([[False, False],
       [ True, False]])

In [147]:
relu = Relu()

In [148]:
relu.forward(x)

In [151]:
dout = np.array([[5.0,6.0],[7.0,8.0]])

In [152]:
relu.backward(dout)

array([[5., 6.],
       [0., 8.]])

---------------------------

In [154]:
X = np.random.rand(2)
W = np.random.rand(2,3)
B = np.random.rand(3)

In [155]:
X

array([0.07853178, 0.7233189 ])

In [156]:
Y = np.dot(X,W) +B

In [157]:
Y

array([1.30961835, 1.03049783, 0.72520172])

------------------------------------

In [167]:
Y.T.shape

(3,)

In [170]:
Y.T

array([1.30961835, 1.03049783, 0.72520172])

--------------------------------------------

In [176]:
x_dot_W = np.array([[0,0,0],[10,10,10]]) #3 * 2
B = np.array([1,2,3]) # 3* 1

In [177]:
dy = np.array([[1,2,3],[4,5,6]])

In [178]:
db = np.sum(dy, axis=0)

In [180]:
db

array([5, 7, 9])

-----------------------------------

In [190]:
class Affine :
    def __init__(self, W, b) :
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
    def forward(self, x): 
        self.x = x
        out = np.dot(x, self.W)  + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout,self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis = 0)
        
        return dx

In [191]:
from common.functions import *

In [194]:
class SoftmaxWithLoss :
    def __init__(self) :
        self.loss = None
        self.y = None
        self.t = None
        
    def forword(self, x, t) :
        self.t = t
        self.y =softmax()
        self.loss = cross_entropy_error(self.y,self.t)
        
        return self.loss
    
    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = self.y -self.t / batch_size
        
        return dx